test key file

diff --git a/.github/workflows/infra-wordpress.yml b/.github/workflows/infra-wordpress.yml
--- a/.github/workflows/infra-wordpress.yml
+++ b/.github/workflows/infra-wordpress.yml
@@ -36,18 +36,18 @@ jobs:
         run: |
             echo "AWS credentials are configured"
 
-      - name: Wordpress_key
-        env:
-          WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
-        run: |
-          mkdir -p ~/.ssh
-          echo "Length of WORDPRESS_KEY: ${#WORDPRESS_KEY}"
-          echo "WORDPRESS_KEY" | base64 --decode > ~/.ssh/id_rsa
-          echo "$WORDPRESS_KEY" | base64 --decode > ~/.ssh/id_rsa || {
-            echo "Error decoding WORDPRESS_KEY"; exit 1;
-          }
+      # - name: Wordpress_key
+      #   env:
+      #     WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
+      #   run: |
+      #     mkdir -p ~/.ssh
+      #     echo "Length of WORDPRESS_KEY: ${#WORDPRESS_KEY}"
+          
+      #     echo "$WORDPRESS_KEY" | base64 --decode > ~/.ssh/id_rsa || {
+      #       echo "Error decoding WORDPRESS_KEY"; exit 1;
+      #     }
     
-          chmod 600 ~/.ssh/id_rsa
+      #     chmod 600 ~/.ssh/id_rsa
       - name: Terraform Init
         run: terraform init
 
